name: na01

services:
  dev:
    image: node:lts-alpine
    working_dir: /repo
    volumes:
      - repo:/repo
    command:
      - sleep
      - infinity
    stop_signal: SIGKILL
    env_file:
      - .env

volumes:
  repo:
